### ISSUE TITLE
data added to range not support utf8

### ISSUE THREAD

**Issue by amirdaee** [OfficeDev/script-lab-2017#890]
hi dear
when i use uft8 character in data and add to range, it's not show correctly.
pleas see this image [here](https://skillpro.ir/wp-content/uploads/2018/12/utf8-support.png).

**Comment by Zlatkovsky** [comment]
That's very interesting.  A couple of follow-up questions:
1. Can you type in these characters manually into the cells?  *(This would help isolate if it's an OS/Excel issue)*
2. Have you tried with a regular add-in (outside of Script Lab)?  *(This will help isolate if it's a Script Lab vs. general API/programmability issue).*

**Comment by Zlatkovsky** [comment]
@amirdaee , ping.

**Comment by amirdaee** [comment]
@Zlatkovsky   it's automatically solved!!!

these character is Persian alphabet ([wiki here](https://en.wikipedia.org/wiki/Persian_alphabet)) and not problem when type directly in excel.

i use Microsoft document and create add in with JQuery from [here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio).

when i add value to excel with add-in it's ok. also when i change Script lab value, it's work correctly!! picture is [here](https://skillpro.ir/wp-content/uploads/2019/01/excel-add-in.png).

thanks for your attention.

**Comment by Zlatkovsky** [comment]
OK, glad to hear that it's resolved (and as such, closing the issue).

A few days ago, we had shipped a brand-new version of Script Lab (https://developer.microsoft.com/en-us/office/blogs/announcing-script-lab-react/), and it might be that the issue got solved through that massive refactoring.

If the issue comes back, just let us know.

Best!
~ Michael
